# Generated by Django 4.1.5 on 2023-01-18 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ongoing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cosplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time_created', models.TimeField(default=datetime.datetime(2023, 1, 18, 15, 21, 53, 950587))),
                ('no_images', models.ImageField(default=0, upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosplay.cosevent')),
            ],
        ),
    ]
